function convertToEmoji() {
    let textInput = document.getElementById("textInput").value;
    let output = textInput
        .replace(/\bhappy\b/gi, '😊')
        .replace(/\blove\b/gi, '❤️')
        .replace(/\bheart\b/gi, '💖')
        .replace(/\bsad\b/gi, '😢')
        .replace(/\bsun\b/gi, '☀️')
        .replace(/\bcat\b/gi, '🐱')
        .replace(/\bdog\b/gi, '🐶')
        .replace(/\blaugh\b/gi, '😂')
        .replace(/\bsmile\b/gi, '😄')
        .replace(/\bbook\b/gi, '📚')
        .replace(/\bcomputer\b/gi, '💻')
        .replace(/\bphone\b/gi, '📱')
        .replace(/\bpizza\b/gi, '🍕')
        .replace(/\bcoffee\b/gi, '☕')
        .replace(/\bcake\b/gi, '🎂')
        .replace(/\bcar\b/gi, '🚗')
        .replace(/\bbike\b/gi, '🚲')
        .replace(/\bflower\b/gi, '🌸')
        .replace(/\bstar\b/gi, '⭐')
        .replace(/\bmoon\b/gi, '🌙')
        .replace(/\btree\b/gi, '🌳')
        .replace(/\bfire\b/gi, '🔥')
        .replace(/\bapple\b/gi, '🍎')
        .replace(/\bbanana\b/gi, '🍌')
        .replace(/\bpear\b/gi, '🍐')
        .replace(/\bcherry\b/gi, '🍒')
        .replace(/\brain\b/gi, '🌧️')
        .replace(/\bwind\b/gi, '💨')
        .replace(/\bsnow\b/gi, '❄️')
        .replace(/\bbus\b/gi, '🚌')
        .replace(/\btrain\b/gi, '🚆')
        .replace(/\brocket\b/gi, '🚀')
        .replace(/\balien\b/gi, '👽')
        .replace(/\bghost\b/gi, '👻')
        .replace(/\bking\b/gi, '👑')
        .replace(/\bqueen\b/gi, '👸')
        .replace(/\bsword\b/gi, '⚔️')
        .replace(/\bshield\b/gi, '🛡️')
        .replace(/\bkey\b/gi, '🔑')
        .replace(/\block\b/gi, '🔒')
        .replace(/\bdoor\b/gi, '🚪')
        .replace(/\bhouse\b/gi, '🏠')
        .replace(/\bflag\b/gi, '🏳️')
        .replace(/\bearth\b/gi, '🌍')
        .replace(/\bunicorn\b/gi, '🦄')
        .replace(/\blion\b/gi, '🦁')
        .replace(/\belephant\b/gi, '🐘')
        .replace(/\btiger\b/gi, '🐅')
        .replace(/\bpanda\b/gi, '🐼')
        .replace(/\bmonkey\b/gi, '🐒')
        .replace(/\bfish\b/gi, '🐟')
        .replace(/\bzebra\b/gi, '🦓')
        .replace(/\bchicken\b/gi, '🐔')
        .replace(/\bcow\b/gi, '🐄')
        .replace(/\bkoala\b/gi, '🐨')
        .replace(/\bsnake\b/gi, '🐍')
        .replace(/\bbunny\b/gi, '🐰')
        .replace(/\bhamster\b/gi, '🐹')
        .replace(/\brobot\b/gi, '🤖')
        .replace(/\bairplane\b/gi, '✈️');

    document.getElementById("output").innerHTML = output;
}
